[FEAT] Adding command resend
diogocezar/pizzaiolo pull request #42
Opened 2022-10-29 21:30 UTC by Joao208

2022-10-29 22:29 UTC, diogocezar requested changes

2022-10-29 22:29 UTC, diogocezar commented on src/app.controller.ts
> +  command(@Body() payload: any): Promise<string> {
Acho que podemos já tipar aqui neh o payload.

2022-10-29 22:29 UTC, diogocezar commented on src/app.service.ts
> +    // if (!foundPullRequest) {
Remover aqui?

2022-10-29 22:29 UTC, diogocezar commented on src/app.service.ts
> +    console.log(payload)
Remover esse log?

2022-10-29 22:29 UTC, diogocezar commented on src/app.service.ts
> +  async command(payload: any): Promise<any> {
Usar o mesmo tipo aqui no payload.

2022-10-29 22:29 UTC, diogocezar commented on src/app.service.ts
> +  async command(payload: any): Promise<any> {
Lembrar de tipar o retorno também.

2022-10-29 22:29 UTC, diogocezar commented on src/app.service.ts
> +    const PRurl = payload.text
Variável mais explicativa? `pullRequestUrl`

2022-10-29 22:29 UTC, diogocezar commented on src/app.service.ts
> +      attachments: formatAttachment({
Esse kra é opcional, pq precisamos enviar com ele todo vazio?

2022-10-30 17:54 UTC, Jott4 approved these changes

2022-10-30 19:29 UTC, diogocezar commented on docs/SLACK_CONFIG.md
> +Then, select "From an app manifest" option, and past the json `app_manifest_example.json`, of this root of this project. And change the `<Your bot's display name>` string, by your but name, and can d
Acho que eu havia renomeado todos os arquivos para `kebab-case`.

2022-10-30 19:31 UTC, Joao208 commented on docs/SLACK_CONFIG.md
> +Then, select "From an app manifest" option, and past the json `app_manifest_example.json`, of this root of this project. And change the `<Your bot's display name>` string, by your but name, and can d
Não é esse PR aqui man? #40

2022-10-30 19:32 UTC, diogocezar commented on src/app.controller.ts
> +  @Post('/interactivity')
Aqui precisamos de um Guard para saber que a mensagem veio realmente do Slack. (Pode ficar para uma versão posterior)

2022-10-30 19:33 UTC, diogocezar approved these changes

2022-10-30 19:49 UTC, merged